### ISSUE TITLE
can  i use other features instead of normal?

### ISSUE THREAD

**Issue by brotherNanNan** [Microsoft/O-CNN#22]
if i have R,G,B and other features of each point, how should i put them into the octree? thks

**Comment by wang-ps** [comment]
Yes, RGB and other features can be used. Probably the results can be improved.
To this end, you just need to modify the code about octree construction and OctreeDatabaseLayer.
It is is not that difficult. 
From the original code,  you can identify where the normal signal is processed, and then modify the relevant code accordingly.
If you still have any problems, feel free to mail me.

**Comment by brotherNanNan** [comment]
@wang-ps  thank you

**Comment by Luckick** [comment]
> Yes, RGB and other features can be used. Probably the results can be improved.
> To this end, you just need to modify the code about octree construction and OctreeDatabaseLayer.
> It is is not that difficult.
> From the original code, you can identify where the normal signal is processed, and then modify the relevant code accordingly.
> If you still have any problems, feel free to mail me.

Hi Pengshuai,

I have revised octree construction and OctreeDatabaseLayer. 
In OctreeDatabaseLayer, I revise data_shape = { batch_size_, 3, 8, 1 }; to data_shape = { batch_size_, my_signal_channel, 8, 1 };
Another change is I change the problem to regression, so I revise the last layer to EuclideanLoss and output channel is 1.

When I try to train, I get error == cudaSuccess (77 vs. 0) error (details are showing below).
Do you have any hints this error might due to?
I have checked GPU usage and reduce batch size but does not work for me.
Many Thanks!


F0126 06:52:08.965098 103404 math_functions.cu:79] Check failed: error == cudaSuccess (77 vs. 0)  an illegal memory access was encountered
*** Check failure stack trace: ***
F0126 06:52:08.965099 103409 math_functions.cpp:91] Check failed: error == cudaSuccess (77 vs. 0)  an illegal memory access was encountered
*** Check failure stack trace: ***
