### ISSUE TITLE
Automate the whole pipeline

### ISSUE THREAD

**Issue by wang-ps** [Microsoft/O-CNN#24]
Help wanted!
The whole pipeline includes building the code (under windows or linux platform), generating the octree dataset, and running the related experiments, which contains many trivial details.
Can anyone help to automate this process, via Python or other script languages,  to save users' time?

**Comment by dapisani** [comment]
I have a Dockerfile which has all the libraries/scripts necessary to automatically download ModelNet40, convert it to octrees and train.  I am in the processing of cleaning it up.

One thing I wanted to run by you is in your visual scanner

1.  It had some windows specific filesystem calls. I had to take a dependency on boost::filesystem this is being folded more or less into std::filesystem in c++17.  You can see the changes [here](https://github.com/dapisani/O-CNN-1/commit/b8d2222440972bccf944ed51d97e283b8f351e4c).

2. Some of the OFF files broke down in your visual scanner due to CGal collapsing as you mention. I changed the code to normalize the maximum extents of the OFF files to be 1.

With those changes I was able to automate everything end to end. 

If you would like those changes on your visual scanner. I can clean it up and do a pull request for that. And then, do a pull request on this OCNN repo with my Dockerfile and instructions how to run it.

**Comment by wang-ps** [comment]
OK! Thank you! 
Fine, I would like to accept your changes.

**Comment by dapisani** [comment]
I've sent a pull request for your virtual scanner.  After that is integrated I will do a pull request for this repo with the automation code.
