### ISSUE TITLE
question about IoU

### ISSUE THREAD

**Issue by chengchengxuxu** [Microsoft/O-CNN#34]
I use the test command in your readme for part segmentation,and I set the iterations are 10,  and I got ten pairs of files(predicted and groundtruth),but how can I use these to compute mIoU?  For example, as I known,the plane（02691156） has four parts,but in one of my files, the groundtruth just have -1,0,1,2,and the predicted have 0,1,2, so is this inconsistent with four parts?  
Furthermore,if the groundtruth's one line is -1,and the predicted's correspond line is 0 or 1 or 2,  how do you judge it's true positives or false positives or false negatives?
![true](https://user-images.githubusercontent.com/43060009/45584896-fd4a0480-b90d-11e8-8d20-b585d3b808e0.png)

**Comment by wang-ps** [comment]
If the ground-truth lebel is -1, it means that the octree node is empty, so just ignore the corresponding prediction. 
Althrough the max part number of the plane is 4, some of them may contain only 3 or even 2 parts. 
So it is valid that  the ground-truth labels contain only -1, 0, 1 and 2.

**Comment by wang-ps** [comment]
For the first question: 
The outputs are the labels of the deepest octree nodes. Since the octrees for different objects are different, the number of deepest octree nodes are also variant. 

For the second question:
The octree is built from a dense point cloud with segmentation labels. For each of the deepest octree node, there is a corresponding ground-truth segmentation label.

**Comment by songyadong106** [comment]
@chengchengxuxu 
@wang-ps 
![image](https://user-images.githubusercontent.com/49023424/77981316-2b4e3880-733c-11ea-9187-13887848bdba.png)

hello, I use the test command in your readme for part segmentation,and I set the iterations are 100, but I didn't got 100 pairs of files(predicted and groundtruth),  can you help me ?
