### ISSUE TITLE
"PoolingParameter_RoundMode" is undefined

### ISSUE THREAD

**Issue by xiaoshuang112** [microsoft/O-CNN#60]
when I put the caffe code into the bvlc caffe,it appear the error like this when I build the code
"./include/caffe/layers/pooling_layer.hpp(54): error: identifier "PoolingParameter_RoundMode" is undefined"

**Comment by wang-ps** [comment]
According to the message you provided, it seems that the error is not caused by our code. I suggest you  build the original Caffe without our code first.

**Comment by xiaoshuang112** [comment]
I have built the original Caffe(bvlc) without error,when I put your code into the bvlc caffe,it appears

**Comment by wang-ps** [comment]
Did you build Caffe with version `6bfc5ca`? I have successfully built the code on Ubnutu with the instructions provided in the readme. 
According to your error message "PoolingParameter_RoundMode", this is caused by the pooling parameters defined in file caffe.proto. I have never modified the pooling parameter.

**Comment by xiaoshuang112** [comment]
I have successfully built the code by correct the proto file ,maybe it,s the problem of my PC，thank you very much
